### ISSUE TITLE
Could not find module "@angular-devkit/build-angular"

### ISSUE THREAD

**Issue by bessalahAmar** [rpaschoal/ng-chat-nodejs#3]
After i run "ng serve -o" , i get this :

```
Could not find module "@angular-devkit/build-angular" from "C:\\Users\\PC738\\Desktop\\Angular-chat\\ng-chat-nodejs\\angular-cli".
Error: Could not find module "@angular-devkit/build-angular" from "C:\\Users\\PC738\\Desktop\\Angular-chat\\ng-chat-nodejs\\angular-cli".
    at Object.resolve (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\node\resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect.js:132:40)
    at Observable._trySubscribe (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:43:25)
    at Observable.subscribe (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:29:22)
    at DoOperator.call (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\tap.js:29:23)
    at Observable.subscribe (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:24:22)
    at C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (C:\Users\PC738\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:72:14)
```

**Comment by rpaschoal** [comment]
Just install the dependency locally, it should fix this message. I believe this is a hiccup from running ng update on the angular CLI and it not updating the dev dependencies accordingly.

I suggest you have a look at this repository as it is newer: https://github.com/rpaschoal/ng-chat-netcoreapp

**Comment by bessalahAmar** [comment]
thanks ,
